sudo: required
dist: trusty
language: java
jdk:
- openjdk11
branches:
  only:
  - develop
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: WpUxpXyekMkdKM1Mcxge0C3bbWZ+CnB75Cmqd69qbcTk1XRSumdwShsb38GXYUxN0/vvVsalMcbLrsg4j/7UMu7qRa9Ph4A2FEACfSASYpNtQaH5LxZqbIcOF2wi+KSYVgT5ezMxsOVlcmLC8LYTF6tKJfOTx1fHhRWXSQdSO4e9hmqbl96aK9g3AEVIF7yP1LYHC1eGu1S2tfIH6nDyuxOSrlK7bvDClywkIYDv1UpXkOLABFNARaJ8MiUaEDe5rWuRERCMLdOnDlkaEkQvwtmGBhbNBDP/30cYt0KPZPJeKnO7JM3/VPBz3YGp6Nuu++JnmQO5H3W7K8VwwajxcN3fO6xRnxIDc9y7vZeToGxqJ5fbS9tWTtiXg7kRGdINO1c2Gz9fYxoTsZVZkijmDE1nHe+FQlUx/xyiQFLwyFPhNT21ES5hrCvxn6vrRbKkmiaNJH5488hQ3LMu0ZN7uUFQHzk/mLmebXn/mpKN6ma3PbVrzpV8M7Z2tGfH1ACp/LveBIZAmFYYm2B0tsxsx7xrw47BhOrKCH+8w7PiLBRX+DcUAg8YZnXjSQMSTT8/R5Qfs5IbdF+IlJZWhzgcvjXYA2WrrAwYrdQ9EibUn3m5lP38LrhQur043HGTGBbZLizDbq+6CUDGA9lGZ0+NnecUh09oZmAaa5jgCJQ3mvs=
install: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=false clean deploy
  --settings .m2/travis-settings.xml"
script: "[ ${TRAVIS_PULL_REQUEST} = 'false' ] && mvn -DskipTests=true clean --settings
  .m2/travis-settings.xml"
env:
  global:
  - CEDAR_HOST=metadatacenter.orgx
  - CEDAR_ADMIN_USER_API_KEY=1234
  - CEDAR_NEO4J_HOST=127.0.0.1
  - CEDAR_NEO4J_USER_NAME=neo4j
  - CEDAR_NEO4J_USER_PASSWORD=password
  - CEDAR_NEO4J_BOLT_PORT=7687
  - CEDAR_MONGO_HOST=127.0.0.1
  - CEDAR_MONGO_PORT=27017
  - CEDAR_MONGO_APP_USER_NAME=cedarUser
  - CEDAR_MONGO_APP_USER_PASSWORD=password
  - CEDAR_OPENSEARCH_HOST=127.0.0.1
  - CEDAR_OPENSEARCH_TRANSPORT_PORT=9300
  - CEDAR_REDIS_PERSISTENT_HOST=127.0.0.1
  - CEDAR_REDIS_PERSISTENT_PORT=6379
  - CEDAR_MONITOR_HTTP_PORT=9014
  - CEDAR_MONITOR_ADMIN_PORT=9114
  - CEDAR_MONITOR_STOP_PORT=9214
  - CEDAR_USER_HTTP_PORT=9005
  - CEDAR_LOG_MYSQL_HOST=127.0.0.1
  - CEDAR_LOG_MYSQL_PORT=3306
  - CEDAR_LOG_MYSQL_DB=cedar_log
  - CEDAR_LOG_MYSQL_USER=cedar_log_user
  - CEDAR_LOG_MYSQL_PASSWORD=cedar_log_password
  # BMIR_NEXUS_USERNAME
  - secure: cd0nxQ22WEKPkRb+0QH4GQ4ZOm98cvWPKbWXz1bBEEor0JHfBZCdHQJsXKrOZXmOnwBcLbkq1r3rPwrIiooDHpNUA19QLbdcn2sxFGuWz3zUdy0lOyW8LeKIxy7NvT4SG6hwJUI8JAZuS5kIxxlBp4hk1fZig5hdUtAR0Mxq6lvoyFl8ArpPCcG4qcQR3/sbLBCCRfGbLe4UuVscmkNOPosfaT7WjoY/yWSPZOpIL++yv79JEU002xMQ+T94WpzZSQH+T7cFv+3Ik2v1aaYrWEcG47O+v+teNji1eNa85dh0hiUIpp8QOwsCRYhlHKRBnH+EVhAk5inAN5Bah/FyTURvm9/0NLeRHn7TpGNADnVGJ+pi5P5wAEkXDM+bI8VpxU2dMOnYvzqOx+1G9XF/MzVXb3IWRWBFlmxG1NIojhjRyQRqSGx/27GNy02PYaXHgPLM6HYLF34uitOjjpv1kIxhEPnYs7/G3920aUucNX4OYSwQb8DKU1d/gGIrG6mKS9vhze/LAwBUuWAOzonTKL3FrfkeytG95WAa+wUM3uHPna80cY2gk8aEVRAw652IQid0scg91kDlmXn3CwSD5wotoIuipRDdR8i+ZFLQNKcnOj57uZIocDNpSnjCfrolbQeJjT1nHTNT+cbM5igRN9gUwAh8uzOb2WixmO+XCbc=
  # BMIR_NEXUS_PASSWORD
  - secure: ab+YMMgAKDt9G5CqtjB7neXiNamMcMr5zKu+ryDmqHkXoulsxC45Ak5JeIernvcIB5uWim8u0enH954XpDMs8tTPdxP+CIQFe/5JKBt2wqpO5U8XOIKb1nfoXhBjYbi2OMqqX6ZVfY7XvdttcFi5H05eQurQ+o0Qbd2WNC2z+vgXJb+tJ7pICNquUsWGCQqxtpM0VCPIsw9JRVNgJu1XWD+lQtq4PoUgBRS0NyKW3NKctr398Sk/fUCb32n4pJD3B2VGftqYekG+dKAgHRkWdGDXCY5rYev+BJvRRDdlksXW0E65VILQDRCezZuXPm4GIqWzFkdVO9X6ZipwQfqEbbRLoMp2PWdzTARtZe0Z+XwazddycDJ1VJlSE1/rb42h3wL73kRnDHoVbLN+y52uatrLA2Fsddh210AvPJFn5rJL1hE22ynZUNPwsY3lgsT+ibefzAWcGatnLeepz3/WIUcq6uZqiCYSaHfW2hXT3iU71Sg5nDKXLeG+xKd6TAivvTTtu+HQfl88nw66TdOmQPUkQT09LwK4Xgw2S/i6348HjUoGr/GGATkhlOEnGS9qSMkvywmmkxMkxtiwJan++3s/PvNld4pAMBlay9pxIjbTbyd6JVvquVVCHzhxU6EJZHaD98CxzM4PqNn8hYDE1k1858+TzCOOU5h6lfoxDGM=
